In [1]:
import torch

In [2]:
# 初始化1*3和2*1矩阵
M = torch.rand(1, 3) # rand  0-1伪随机数
N = torch.randn(2, 1) # randn 标准正态分布
M, N
M = torch.tensor([[1, 2, 3]], dtype=torch.float32) # tensor()创建张量
N = torch.tensor([[1], [2]], dtype=torch.float32)
print(f"M: {M}")
print(f"N: {N}")

M: tensor([[1., 2., 3.]])
N: tensor([[1.],
        [2.]])


In [3]:
# 方式一：直接相加，自动进行广播
M - N # 1*3 + 2*1 -> 2*3(复制列) + 2*3(复制行)

tensor([[ 0.,  1.,  2.],
        [-1.,  0.,  1.]])

In [4]:
# 方式二：torch.sub(input, other, *, alpha=1, out=None)
torch.sub(M, N)

tensor([[ 0.,  1.,  2.],
        [-1.,  0.,  1.]])

In [5]:
M.sub(N)

tensor([[ 0.,  1.,  2.],
        [-1.,  0.,  1.]])

In [6]:
##### 实验1.2  

In [7]:
P = torch.randn(3, 2) * 0.01
Q = torch.randn(4, 2) * 0.01
print(f"P: {P}")
print(f"Q: {Q}")

P: tensor([[ 0.0042, -0.0105],
        [ 0.0030,  0.0063],
        [-0.0081, -0.0015]])
Q: tensor([[-0.0011,  0.0161],
        [-0.0161, -0.0027],
        [ 0.0044,  0.0082],
        [ 0.0092, -0.0101]])


In [8]:
# 计算Q的转置
# Q_t = Q.T
# Q_t = Q.t()
Q_t = Q.transpose(0, 1)
print(f"Q_t： {Q_t}")

Q_t： tensor([[-0.0011, -0.0161,  0.0044,  0.0092],
        [ 0.0161, -0.0027,  0.0082, -0.0101]])


In [9]:
P.matmul(Q_t)
print(f"P @ Q_t: {P @ Q_t}")

P @ Q_t: tensor([[-1.7397e-04, -3.8876e-05, -6.7811e-05,  1.4449e-04],
        [ 9.8341e-05, -6.4987e-05,  6.5175e-05, -3.6247e-05],
        [-1.4356e-05,  1.3430e-04, -4.8043e-05, -5.9915e-05]])


In [10]:
#### 实验1.3

In [11]:
# x = torch.tensor(1, requires_grad=True)
x = torch.tensor(1.0, requires_grad=True, dtype=torch.float32)
y1 = x ** 2
with torch.no_grad():
    # 在不需要梯度计算的上下文中执行
    y2 = x ** 3
    print("No gradient calculation needed for y2")
y3 = y1 + y2
print(f"x: {x}\ny1: {y1}, y2: {y2}\ny3: {y3}")

No gradient calculation needed for y2
x: 1.0
y1: 1.0, y2: 1.0
y3: 2.0


In [12]:
# 梯度计算
y3.backward()  # 计算梯度
print(f"x.grad: {x.grad}")  # 输出梯度

x.grad: 2.0
